### ISSUE TITLE
Data documentation

### ISSUE THREAD

**Issue by AmanSufian** [HaritzHaykal/Y1-SECPH-02#20]
![Image](https://github.com/user-attachments/assets/45e61891-2854-457f-8893-d2dfa88e6a8a)

Closed the Google Form from accepting responses and collected the data to make data visualization.

https://onedrive.live.com/personal/3e47c3a9d03a83ec/_layouts/15/Doc.aspx?resid=3E47C3A9D03A83EC!s6a165fdb02f04d13811bb41d3b48f7a4&cid=3e47c3a9d03a83ec&migratedtospo=true&app=Excel

![Image](https://github.com/user-attachments/assets/38c5b4be-ca2e-4005-9df4-e6a288ba6a9c)

Do some calculations and create a pie chart based on data.

**Comment by Aunisofia** [comment]
![Image](https://github.com/user-attachments/assets/683403d0-df6f-4c82-ba00-d85f9e08beed)

Touch up and add descriptions in the pie chart by using Canva

**Comment by umainur** [comment]
![Image](https://github.com/user-attachments/assets/50f97d50-d757-422f-8da8-b79b6a7cf3c5)

![Image](https://github.com/user-attachments/assets/b9e96bda-1c68-4720-9a18-948ef937c640)


Designing the pie chart with the information given from Auni
