### ISSUE TITLE
Second Physical Meeting

### ISSUE THREAD

**Issue by AmanSufian** [HaritzHaykal/Y1-SECPH-02#21]

**Comment by umainur** [comment]
![Image](https://github.com/user-attachments/assets/9d4fd8db-c8c8-4f49-ba17-57ed9282b304)


discussion topics :

- aman and haykal will interview the store manager to find out more about the problems they face when using the dining section in UTMSmart 
- umairah and auni will interview food riders as users of delivery platform to identify the issues related to technical problems on UTMSmart.
- group reminder: to collect all data for all Arked in UTM before semester break to avoid any disruptions when building the system prototype which we plan to focus on more after the break
