### ISSUE TITLE
Procced with collect data about all the cafe

### ISSUE THREAD

**Issue by AmanSufian** [haritzhaykal/Y1-SECPH-02#22]

**Comment by umainur** [comment]
![Image](https://github.com/user-attachments/assets/3e9e527a-265e-43b0-b788-6986cadb39cb)

**Comment by umainur** [comment]
ARKED/CAFE NO 3
![Image](https://github.com/user-attachments/assets/79990a0c-33da-44f5-8505-c0b4850c91bc)
![Image](https://github.com/user-attachments/assets/6aa05fc5-a47f-4640-8dca-82aba3356a5d)
